package icalc;


import java.awt.ComponentOrientation;
import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author bushra
 */
public class frmBinary extends javax.swing.JFrame implements ActionListener
{

    /**
     * Creates new form frmMain
     */
    public frmBinary() 
    {
        initComponents();
        
        tfDigitScreen.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT); // to enable right to left text entry in textfield
        this.setLocationRelativeTo(null); // for centering form on screen 
        
        
        btnDigit1.addActionListener(this);
        btnDigit0.addActionListener(this);
        btnAdd.addActionListener(this);
        btnSubtract.addActionListener(this);
        btnMultiply.addActionListener(this);
        btnEquals.addActionListener(this);
    }
    
    

    boolean isCalculating = true; // flag variable
    
    BinaryCalculator cal = new BinaryCalculator(0);
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfDigitScreen = new javax.swing.JTextField();
        btnDigit1 = new javax.swing.JButton();
        btnDigit0 = new javax.swing.JButton();
        btnMultiply = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnEquals = new javax.swing.JButton();
        btnSubtract = new javax.swing.JButton();
        btnAC = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnFile = new javax.swing.JMenu();
        btnExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        btnBasic = new javax.swing.JMenuItem();
        btnTrigonometric = new javax.swing.JMenuItem();
        btnMatrix = new javax.swing.JMenuItem();
        btnLogarithmic = new javax.swing.JMenuItem();
        btnRadical = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tfDigitScreen.setEditable(false);
        tfDigitScreen.setBackground(new java.awt.Color(102, 102, 102));
        tfDigitScreen.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        tfDigitScreen.setForeground(new java.awt.Color(204, 204, 204));
        tfDigitScreen.setText("0");
        tfDigitScreen.setBorder(null);

        btnDigit1.setBackground(new java.awt.Color(102, 102, 102));
        btnDigit1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnDigit1.setForeground(new java.awt.Color(255, 255, 255));
        btnDigit1.setText("1");
        btnDigit1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        btnDigit0.setBackground(new java.awt.Color(102, 102, 102));
        btnDigit0.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnDigit0.setForeground(new java.awt.Color(255, 255, 255));
        btnDigit0.setText("0");
        btnDigit0.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        btnMultiply.setBackground(new java.awt.Color(255, 153, 0));
        btnMultiply.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnMultiply.setForeground(new java.awt.Color(255, 255, 255));
        btnMultiply.setText("X");
        btnMultiply.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        btnAdd.setBackground(new java.awt.Color(255, 153, 0));
        btnAdd.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("+");
        btnAdd.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        btnEquals.setBackground(new java.awt.Color(255, 153, 0));
        btnEquals.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnEquals.setForeground(new java.awt.Color(255, 255, 255));
        btnEquals.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnEquals.setLabel("=");

        btnSubtract.setBackground(new java.awt.Color(255, 153, 0));
        btnSubtract.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnSubtract.setForeground(new java.awt.Color(255, 255, 255));
        btnSubtract.setText("-");
        btnSubtract.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        btnAC.setBackground(new java.awt.Color(102, 102, 102));
        btnAC.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnAC.setForeground(new java.awt.Color(255, 255, 255));
        btnAC.setText("AC");
        btnAC.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnACActionPerformed(evt);
            }
        });

        btnFile.setText("File");

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        btnFile.add(btnExit);

        jMenuBar1.add(btnFile);

        jMenu2.setText("Mode");

        btnBasic.setText("Basic");
        btnBasic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBasicActionPerformed(evt);
            }
        });
        jMenu2.add(btnBasic);

        btnTrigonometric.setText("Trigonometric");
        btnTrigonometric.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrigonometricActionPerformed(evt);
            }
        });
        jMenu2.add(btnTrigonometric);

        btnMatrix.setText("Matrix");
        btnMatrix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatrixActionPerformed(evt);
            }
        });
        jMenu2.add(btnMatrix);

        btnLogarithmic.setText("Logarithmic");
        btnLogarithmic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogarithmicActionPerformed(evt);
            }
        });
        jMenu2.add(btnLogarithmic);

        btnRadical.setText("Radical");
        btnRadical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRadicalActionPerformed(evt);
            }
        });
        jMenu2.add(btnRadical);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfDigitScreen, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAC, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnDigit1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDigit0, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSubtract, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnEquals, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tfDigitScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAC, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSubtract, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDigit1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDigit0, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEquals, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    public void actionPerformed(java.awt.event.ActionEvent evt) 
    {
        String btnClicked = evt.getActionCommand();
        
                if('0' <= btnClicked.charAt(0) && btnClicked.charAt(0) <= '9') 
                {
                    if(isCalculating)
                      tfDigitScreen.setText(btnClicked);
                    else
                      tfDigitScreen.setText(tfDigitScreen.getText() + btnClicked);
                    isCalculating = false;
                } 
                else 
                {
                    if(isCalculating) 
                    {
                      if(btnClicked.equals("-")) 
                      {
                        tfDigitScreen.setText(btnClicked);
                        isCalculating = false;
                      } 
                      else
                        cal.setOperatorType(btnClicked);

                    } 
                    else 
                    {
                      String finalR = cal.Calculate(tfDigitScreen.getText());
                      tfDigitScreen.setText("" + finalR);
                      cal.setOperatorType(btnClicked);
                      isCalculating = true;
                    }
                }
        
        

  }
    
    
    private void btnACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnACActionPerformed
        // TODO add your handling code here:
        
        tfDigitScreen.setText("0");
        isCalculating = true;
        cal.ClearAll();
    }//GEN-LAST:event_btnACActionPerformed

    private void btnTrigonometricActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrigonometricActionPerformed
        // TODO add your handling code here:
        
        new frmTrigonometry().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnTrigonometricActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnLogarithmicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogarithmicActionPerformed
        // TODO add your handling code here:
        
        new frmLogarithmic().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnLogarithmicActionPerformed

    private void btnRadicalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRadicalActionPerformed
        // TODO add your handling code here:
        
        new frmRadical().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRadicalActionPerformed

    private void btnBasicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBasicActionPerformed
        // TODO add your handling code here:
        new frmBasic().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBasicActionPerformed

    private void btnMatrixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatrixActionPerformed
        // TODO add your handling code here:
        
        new frmMatrix().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnMatrixActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmBinary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmBinary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmBinary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmBinary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmBinary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAC;
    private javax.swing.JButton btnAdd;
    private javax.swing.JMenuItem btnBasic;
    private javax.swing.JButton btnDigit0;
    private javax.swing.JButton btnDigit1;
    private javax.swing.JButton btnEquals;
    private javax.swing.JMenuItem btnExit;
    private javax.swing.JMenu btnFile;
    private javax.swing.JMenuItem btnLogarithmic;
    private javax.swing.JMenuItem btnMatrix;
    private javax.swing.JButton btnMultiply;
    private javax.swing.JMenuItem btnRadical;
    private javax.swing.JButton btnSubtract;
    private javax.swing.JMenuItem btnTrigonometric;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField tfDigitScreen;
    // End of variables declaration//GEN-END:variables
}
