package icalc;


import java.awt.ComponentOrientation;
import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author bushra
 */
public class frmLogarithmic extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form frmMain
     */
    public frmLogarithmic() {
        initComponents();
        
        tfDigitScreen.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT); // to enable right to left text entry in textfield
        this.setLocationRelativeTo(null); // for centering form on screen 
        
        
        btnDigit1.addActionListener(this);
        btnDigit2.addActionListener(this);
        btnDigit3.addActionListener(this);
        btnDigit4.addActionListener(this);
        btnDigit5.addActionListener(this);
        btnDigit6.addActionListener(this);
        btnDigit7.addActionListener(this);
        btnDigit8.addActionListener(this);
        btnDigit9.addActionListener(this);
        btnDigit0.addActionListener(this);
        btnAdd.addActionListener(this);
        btnSubtract.addActionListener(this);
        btnMultiply.addActionListener(this);
        btnDivide.addActionListener(this);
        btnDigitDot.addActionListener(this);
        btnEquals.addActionListener(this);
    }
    
    

    boolean isCalculating = true; // flag variable
    
    LogarithmicCalculator cal = new LogarithmicCalculator(0);
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfDigitScreen = new javax.swing.JTextField();
        btnDigit2 = new javax.swing.JButton();
        btnDigit1 = new javax.swing.JButton();
        btnDigit3 = new javax.swing.JButton();
        btnDigit4 = new javax.swing.JButton();
        btnDigit5 = new javax.swing.JButton();
        btnDigit6 = new javax.swing.JButton();
        btnDigit7 = new javax.swing.JButton();
        btnDigit8 = new javax.swing.JButton();
        btnDigit9 = new javax.swing.JButton();
        btnDigit0 = new javax.swing.JButton();
        btnDigitDot = new javax.swing.JButton();
        btnDivide = new javax.swing.JButton();
        btnMultiply = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnEquals = new javax.swing.JButton();
        btnSubtract = new javax.swing.JButton();
        btnAC = new javax.swing.JButton();
        btnLog = new javax.swing.JButton();
        btnLog10 = new javax.swing.JButton();
        btnLog1p = new javax.swing.JButton();
        btnRand = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnFile = new javax.swing.JMenu();
        btnExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        btnBasic = new javax.swing.JMenuItem();
        btnBinary = new javax.swing.JMenuItem();
        btnMatrix = new javax.swing.JMenuItem();
        btnTrigonometric = new javax.swing.JMenuItem();
        btnRadical = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tfDigitScreen.setEditable(false);
        tfDigitScreen.setBackground(new java.awt.Color(102, 102, 102));
        tfDigitScreen.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        tfDigitScreen.setForeground(new java.awt.Color(204, 204, 204));
        tfDigitScreen.setText("0");
        tfDigitScreen.setBorder(null);

        btnDigit2.setBackground(new java.awt.Color(102, 102, 102));
        btnDigit2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnDigit2.setForeground(new java.awt.Color(255, 255, 255));
        btnDigit2.setText("2");
        btnDigit2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        btnDigit1.setBackground(new java.awt.Color(102, 102, 102));
        btnDigit1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnDigit1.setForeground(new java.awt.Color(255, 255, 255));
        btnDigit1.setText("1");
        btnDigit1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        btnDigit3.setBackground(new java.awt.Color(102, 102, 102));
        btnDigit3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnDigit3.setForeground(new java.awt.Color(255, 255, 255));
        btnDigit3.setText("3");
        btnDigit3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        btnDigit4.setBackground(new java.awt.Color(102, 102, 102));
        btnDigit4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnDigit4.setForeground(new java.awt.Color(255, 255, 255));
        btnDigit4.setText("4");
        btnDigit4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        btnDigit5.setBackground(new java.awt.Color(102, 102, 102));
        btnDigit5.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnDigit5.setForeground(new java.awt.Color(255, 255, 255));
        btnDigit5.setText("5");
        btnDigit5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        btnDigit6.setBackground(new java.awt.Color(102, 102, 102));
        btnDigit6.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnDigit6.setForeground(new java.awt.Color(255, 255, 255));
        btnDigit6.setText("6");
        btnDigit6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        btnDigit7.setBackground(new java.awt.Color(102, 102, 102));
        btnDigit7.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnDigit7.setForeground(new java.awt.Color(255, 255, 255));
        btnDigit7.setText("7");
        btnDigit7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        btnDigit8.setBackground(new java.awt.Color(102, 102, 102));
        btnDigit8.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnDigit8.setForeground(new java.awt.Color(255, 255, 255));
        btnDigit8.setText("8");
        btnDigit8.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        btnDigit9.setBackground(new java.awt.Color(102, 102, 102));
        btnDigit9.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnDigit9.setForeground(new java.awt.Color(255, 255, 255));
        btnDigit9.setText("9");
        btnDigit9.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        btnDigit0.setBackground(new java.awt.Color(102, 102, 102));
        btnDigit0.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnDigit0.setForeground(new java.awt.Color(255, 255, 255));
        btnDigit0.setText("0");
        btnDigit0.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        btnDigitDot.setBackground(new java.awt.Color(102, 102, 102));
        btnDigitDot.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnDigitDot.setForeground(new java.awt.Color(255, 255, 255));
        btnDigitDot.setText(".");
        btnDigitDot.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        btnDivide.setBackground(new java.awt.Color(255, 153, 0));
        btnDivide.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnDivide.setForeground(new java.awt.Color(255, 255, 255));
        btnDivide.setText("/");
        btnDivide.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        btnMultiply.setBackground(new java.awt.Color(255, 153, 0));
        btnMultiply.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnMultiply.setForeground(new java.awt.Color(255, 255, 255));
        btnMultiply.setText("X");
        btnMultiply.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        btnAdd.setBackground(new java.awt.Color(255, 153, 0));
        btnAdd.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("+");
        btnAdd.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        btnEquals.setBackground(new java.awt.Color(255, 153, 0));
        btnEquals.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnEquals.setForeground(new java.awt.Color(255, 255, 255));
        btnEquals.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnEquals.setLabel("=");

        btnSubtract.setBackground(new java.awt.Color(255, 153, 0));
        btnSubtract.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnSubtract.setForeground(new java.awt.Color(255, 255, 255));
        btnSubtract.setText("-");
        btnSubtract.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        btnAC.setBackground(new java.awt.Color(102, 102, 102));
        btnAC.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnAC.setForeground(new java.awt.Color(255, 255, 255));
        btnAC.setText("AC");
        btnAC.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnACActionPerformed(evt);
            }
        });

        btnLog.setBackground(new java.awt.Color(255, 153, 0));
        btnLog.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnLog.setForeground(new java.awt.Color(255, 255, 255));
        btnLog.setText("ln");
        btnLog.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogActionPerformed(evt);
            }
        });

        btnLog10.setBackground(new java.awt.Color(255, 153, 0));
        btnLog10.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnLog10.setForeground(new java.awt.Color(255, 255, 255));
        btnLog10.setText("log10");
        btnLog10.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnLog10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLog10ActionPerformed(evt);
            }
        });

        btnLog1p.setBackground(new java.awt.Color(255, 153, 0));
        btnLog1p.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnLog1p.setForeground(new java.awt.Color(255, 255, 255));
        btnLog1p.setText("log1p");
        btnLog1p.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnLog1p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLog1pActionPerformed(evt);
            }
        });

        btnRand.setBackground(new java.awt.Color(255, 153, 0));
        btnRand.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnRand.setForeground(new java.awt.Color(255, 255, 255));
        btnRand.setText("Rand");
        btnRand.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnRand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRandActionPerformed(evt);
            }
        });

        btnFile.setText("File");

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        btnFile.add(btnExit);

        jMenuBar1.add(btnFile);

        jMenu2.setText("Mode");

        btnBasic.setText("Basic");
        btnBasic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBasicActionPerformed(evt);
            }
        });
        jMenu2.add(btnBasic);

        btnBinary.setText("Binary");
        btnBinary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBinaryActionPerformed(evt);
            }
        });
        jMenu2.add(btnBinary);

        btnMatrix.setText("Matrix");
        btnMatrix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatrixActionPerformed(evt);
            }
        });
        jMenu2.add(btnMatrix);

        btnTrigonometric.setText("Trigonometric");
        btnTrigonometric.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrigonometricActionPerformed(evt);
            }
        });
        jMenu2.add(btnTrigonometric);

        btnRadical.setText("Radical");
        btnRadical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRadicalActionPerformed(evt);
            }
        });
        jMenu2.add(btnRadical);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfDigitScreen)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDigit0, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDigitDot, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEquals, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnDigit7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnDigit8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnDigit9, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnDigit4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnDigit5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnDigit6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnDigit1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnDigit2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnDigit3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(btnAC, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnSubtract, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnLog, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnLog10, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnLog1p, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnRand, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 25, Short.MAX_VALUE)
                .addComponent(tfDigitScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRand, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAC, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDigit8, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDigit9, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDigit7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDigit5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDigit6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDigit4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDigit2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDigit3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDigit1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSubtract, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnLog, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLog10, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLog1p, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(59, 59, 59)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDigitDot, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDigit0, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEquals, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    public void actionPerformed(java.awt.event.ActionEvent evt) 
    {
        String btnClicked = evt.getActionCommand();
        
        if(!tfDigitScreen.getText().contains("."))
        {
                if('0' <= btnClicked.charAt(0) && btnClicked.charAt(0) <= '9' || btnClicked.equals(".")) 
                {
                    if(isCalculating)
                      tfDigitScreen.setText(btnClicked);
                    else
                      tfDigitScreen.setText(tfDigitScreen.getText() + btnClicked);
                    isCalculating = false;
                } 
                else 
                {
                    if(isCalculating) 
                    {
                      if(btnClicked.equals("-")) 
                      {
                        tfDigitScreen.setText(btnClicked);
                        isCalculating = false;
                      } 
                      else
                        cal.setOperatorType(btnClicked);

                    } 
                    else 
                    {
                      double operand = Double.parseDouble(tfDigitScreen.getText());
                      cal.Calculate(operand);
                      tfDigitScreen.setText("" + cal.getResult());
                      cal.setOperatorType(btnClicked);
                      isCalculating = true;
                    }
                }
        }
        else
        {
            if('0' <= btnClicked.charAt(0) && btnClicked.charAt(0) <= '9' && !(btnClicked.equals("."))) 
                {
                    if(isCalculating)
                      tfDigitScreen.setText(btnClicked);
                    else
                      tfDigitScreen.setText(tfDigitScreen.getText() + btnClicked);
                    isCalculating = false;
                } 
                else 
                {
                    if(isCalculating) 
                    {
                      if(btnClicked.equals("-")) 
                      {
                        tfDigitScreen.setText(btnClicked);
                        isCalculating = false;
                      } 
                      else
                        cal.setOperatorType(btnClicked);

                    } 
                    else 
                    {
                      double operand = Double.parseDouble(tfDigitScreen.getText());
                      cal.Calculate(operand);
                      tfDigitScreen.setText("" + cal.getResult());
                      cal.setOperatorType(btnClicked);
                      isCalculating = true;
                    }
                }
        }
        

  }
    
    
    private void btnACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnACActionPerformed
        // TODO add your handling code here:
        
        tfDigitScreen.setText("0");
        isCalculating = true;
        cal.ClearAll();
    }//GEN-LAST:event_btnACActionPerformed

    private void btnBasicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBasicActionPerformed
        // TODO add your handling code here:
        
        new frmBasic().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBasicActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogActionPerformed
        // TODO add your handling code here:
        
        cal.setOperand(Double.parseDouble(tfDigitScreen.getText()));
        tfDigitScreen.setText(Double.toString(cal.Log()));
    }//GEN-LAST:event_btnLogActionPerformed

    private void btnLog10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLog10ActionPerformed
        // TODO add your handling code here:
        
        cal.setOperand(Double.parseDouble(tfDigitScreen.getText()));
        tfDigitScreen.setText(Double.toString(cal.Log10()));
    }//GEN-LAST:event_btnLog10ActionPerformed

    private void btnLog1pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLog1pActionPerformed
        // TODO add your handling code here:
        
        cal.setOperand(Double.parseDouble(tfDigitScreen.getText()));
        tfDigitScreen.setText(Double.toString(cal.Log1p()));
    }//GEN-LAST:event_btnLog1pActionPerformed

    private void btnRandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRandActionPerformed
        // TODO add your handling code here:
        
        cal.setOperand(Double.parseDouble(tfDigitScreen.getText()));
        tfDigitScreen.setText(Double.toString(cal.Rand()));
    }//GEN-LAST:event_btnRandActionPerformed

    private void btnTrigonometricActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrigonometricActionPerformed
        // TODO add your handling code here:
        
        new frmTrigonometry().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnTrigonometricActionPerformed

    private void btnRadicalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRadicalActionPerformed
        // TODO add your handling code here:
        
        new frmRadical().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRadicalActionPerformed

    private void btnBinaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBinaryActionPerformed
        // TODO add your handling code here:
        
        new frmBinary().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBinaryActionPerformed

    private void btnMatrixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatrixActionPerformed
        // TODO add your handling code here:
        
        new frmMatrix().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnMatrixActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLogarithmic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLogarithmic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLogarithmic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLogarithmic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLogarithmic().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAC;
    private javax.swing.JButton btnAdd;
    private javax.swing.JMenuItem btnBasic;
    private javax.swing.JMenuItem btnBinary;
    private javax.swing.JButton btnDigit0;
    private javax.swing.JButton btnDigit1;
    private javax.swing.JButton btnDigit2;
    private javax.swing.JButton btnDigit3;
    private javax.swing.JButton btnDigit4;
    private javax.swing.JButton btnDigit5;
    private javax.swing.JButton btnDigit6;
    private javax.swing.JButton btnDigit7;
    private javax.swing.JButton btnDigit8;
    private javax.swing.JButton btnDigit9;
    private javax.swing.JButton btnDigitDot;
    private javax.swing.JButton btnDivide;
    private javax.swing.JButton btnEquals;
    private javax.swing.JMenuItem btnExit;
    private javax.swing.JMenu btnFile;
    private javax.swing.JButton btnLog;
    private javax.swing.JButton btnLog10;
    private javax.swing.JButton btnLog1p;
    private javax.swing.JMenuItem btnMatrix;
    private javax.swing.JButton btnMultiply;
    private javax.swing.JMenuItem btnRadical;
    private javax.swing.JButton btnRand;
    private javax.swing.JButton btnSubtract;
    private javax.swing.JMenuItem btnTrigonometric;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField tfDigitScreen;
    // End of variables declaration//GEN-END:variables
}
